### ISSUE TITLE
error CDS0001: Error connecting to Dataverse.

### ISSUE THREAD

**Issue by kine** [microsoft/bc2dataverse#3]
Hi,
I am using this tool for few months already, but since last week I am getting this error when I try to generate the proxy table:

```
[Window Title]
Visual Studio Code

[Content]
Error: Microsoft (R) AL Table Proxy Generator version 11.0.11.39772
Copyright (C) Microsoft Corporation. All rights reserved

Authenticating Dataverse using ServiceUri=https://xxxxx.crm4.dynamics.com
error CDS0001: Error connecting to Dataverse. 
Microsoft.Dynamics.Nav.Xrm.Common.XrmException: Failed to connect to Dataverse

Server stack trace: 


Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Dynamics.Nav.Xrm.Common.IXrmService.Connect(String serviceUri, String token)
   at Microsoft.Dynamics.Nav.TableProxyGenerator.XrmMetadataService.CreateXmlMetadataService(String serviceUri, String token) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\Xrm\XrmMetadataService.cs:line 67
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorTool.CreateXrmMetadataService(IList`1 diagnostics, String token) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\TableProxyGeneratorTool.cs:line 92
    
Error: Microsoft (R) AL Table Proxy Generator version 11.0.11.39772
Copyright (C) Microsoft Corporation. All rights reserved

Authenticating Dataverse using ServiceUri=https://xxxxx.crm4.dynamics.com
error CDS0001: Error connecting to Dataverse. 
Microsoft.Dynamics.Nav.Xrm.Common.XrmException: Failed to connect to Dataverse

Server stack trace: 


Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Dynamics.Nav.Xrm.Common.IXrmService.Connect(String serviceUri, String token)
   at Microsoft.Dynamics.Nav.TableProxyGenerator.XrmMetadataService.CreateXmlMetadataService(String serviceUri, String token) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\Xrm\XrmMetadataService.cs:line 67
   at Microsoft.Dynamics.Nav.TableProxyGenerator.TableProxyGeneratorTool.CreateXrmMetadataService(IList`1 diagnostics, String token) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.TableProxyGenerator\TableProxyGeneratorTool.cs:line 92
    

    at c:\Users\xxx\.vscode\extensions\thebc2dataverseteam-msdenmark.bc2dataverse-1.0.0\out\helpers\utils.js:160:48
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at c:\Users\xxx\.vscode\extensions\thebc2dataverseteam-msdenmark.bc2dataverse-1.0.0\out\proxyGen.js:120:28
    at c:\Users\xxx\.vscode\extensions\thebc2dataverseteam-msdenmark.bc2dataverse-1.0.0\out\helpers\utils.js:138:16

[OK]
```

We have checked on AAD side that authentication is successful (first I though that problem is on AAD side because conditional access is used on tenant I am working with). I do not know if the problem is in the tool or it is something on Dataverse side (not expert on this).

Could someone:
1. try that it is working for someone else (problem on my side then...)
2. Tell me what is needed on DataVerse side to be able to connect (used account was working, no known changes were made by administrators on DataVerse side, account should be admin)
Thanks for helping me in triage...

**Comment by Bertverbeek4PS** [comment]
@kine 
For me it is working.
You got this issue if you target the wrong dataverse environment or credentials.
The environment you target you can find in the settings.json in the property bc2dataverse.dataverseServiceUrl

**Comment by kine** [comment]
Thanks @Bertverbeek4PS,
I have checked this and it is ok. It is same as I was using just few days ago. Same settings, same account, but the process fails (and the authentication succeeded on the AAD). I will check with customer if they didn't changed something, but when I open the URL from the settings, I am able to login into the environment. 

Still, the info that it is working for you is valuable for me too. Thanks.

**Comment by Bertverbeek4PS** [comment]
Good luck @kine. If I need to check anything more let me know.
Strange that you can log into the environment with the credentials.

**Comment by kine** [comment]
I have used now the tool through console and when I use altpgen from version 11.0.760646 of AL Language Extension, it fails. Version from 9.5.674382 works. Will try to find the exact version where it stopped to work.

**Comment by kine** [comment]
Version from AL Language 10.5.765371 works (altpgen version 10.5.11.44497).

Version from AL Language 11.0.748446 (BCv22 insider preview, altpgen version 11.0.11.27572) doesn't work.

@Bertverbeek4PS could you try with the AL Language for the BCv22?

**Comment by Bertverbeek4PS** [comment]
@kine 
I have checked also the insider preview and got the same issue.
Version from AL Language 11.0.755021 (altpgen version 11.0.11.34147) doesn't work.
I could now create a new preview build because my docker is failing.

**Comment by Bertverbeek4PS** [comment]
Also with the latest altpgen.exe (version 11.0.11.39772) it isn't working.

**Comment by Bertverbeek4PS** [comment]
@onbuyuka maybe you can help looking what is wrong?
In version 11 we get the "Failed to connect to Dataverse" issue.

**Comment by AntonioBotticella** [comment]
I have this issue too (altpgen.exe version 11.0.11.58421)

**Comment by RaulBogajo** [comment]
Just got the same problem today...

Installing the pre release and just switching to the available Pre-Release version of AL code extension let me generate the proxy table with no issue.

![Screenshot 2023-05-14 134638](https://github.com/microsoft/bc2dataverse/assets/133575881/d0de4e3b-8790-4442-8ab1-c12dc2d51c7b)

**Comment by onbuyuka** [comment]
This issue is fixed in Pre-Release Version and will be available in the next release

**Comment by DuttaSoumya** [comment]
Tried out the latest released  - where the error **occurs**.
![image](https://github.com/microsoft/bc2dataverse/assets/38040179/b54408c6-3822-4cc5-bea1-9dfe2f556ba0)

![image](https://github.com/microsoft/bc2dataverse/assets/38040179/4391b52d-66f6-4a43-a689-bd9c8953f12d)

Tried out also the Pre-Released version, where the error **does not occur**.
![image](https://github.com/microsoft/bc2dataverse/assets/38040179/d9d2b5c5-b35b-4cf3-8f56-8633e7842b81)

Thanks to @onbuyuka for checking up on the issue. Let's wait for the bits to be released, and in the meantime use the workaround to use the pre-release version suggested.
